# Automatically generated by configure - do not modify
SRC_PATH=/home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU
CONFIG_PLUGIN=y
PYTHON=/home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU/build-femu/pyvenv/bin/python3 -B
