# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU
TARGET_DIRS=x86_64-softmmu
GDB=/usr/bin/gdb
RUNC=docker
SUBDIRS=
PYTHON=/home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU/build-femu/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU/build-femu/pyvenv/bin/python3 -B /home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/home/hyunil/Desktop/SKKU_PA/2025/semester2/SA/Lab/FEMU/build-femu/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
